name: fkafka_ffi
description: Use librdkafka via Dart FFI, wraps admin and producer and consumer clients.
version: 1.0.1
homepage: https://github.com/headone/fkafka

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  ffi: ^1.2.1